### ISSUE TITLE
Catch2 v3 integration

### ISSUE THREAD

**Issue by LesleyLai** [approvals/ApprovalTests.cpp#210]
[The new version of Catch2](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md) seems to break a bunch of things for ApprovalTests

**Comment by ricardomatias** [comment]
Any workaround?

**Comment by claremacrae** [comment]
Just to note that we are actively working on this currently, with the help of @Laguna1989:

See:

- https://github.com/approvals/ApprovalTests.cpp/pull/221
- https://github.com/approvals/ApprovalTests.cpp/pull/222

Our next step is to update the documentation, and then we will release it.

> Any workaround?

@ricardomatias, if you wish to read through the changes in the above PRs, you are welcome to try.

Otherwise, it will be released soon, likely within the next few weeks.

**Comment by ricardomatias** [comment]
Thanks @claremacrae. I'm unsure if it's related, but I get a `ApprovalMissingException` (using master branch). I'm linking in cmake via `target_link_libraries(${TEST_BASENAME} ApprovalTests::ApprovalTests Catch2::Catch2WithMain)` and each test file includes a file with:

```cpp
#define APPROVALS_CATCH2_V3
#include "ApprovalTests.hpp"
#include <catch2/catch_all.hpp>

auto defaultReporterDisposer = ApprovalTests::Approvals::useAsDefaultReporter(
    std::make_shared<ApprovalTests::AutoApproveIfMissingReporter>());
auto directoryDisposer = ApprovalTests::Approvals::useApprovalsSubdirectory("snapshots");
```

The `.received.txt` file is created but nothing prompts it to be approved even with `AutoApproveIfMissingReporter`. It's also not clear how ApprovalTests tries to find the diffing tools in the path, but I have visual studio code in the path.

**Comment by claremacrae** [comment]
@ricardomatias Please use the last-released version of Approval Tests until we have fully tested, documented and released Catch2 V3 support. Thanks.

**Comment by claremacrae** [comment]
This is done and will be released soon
