### ISSUE TITLE
Catch2 v3 integration does not work with Catch2 amalgamated releases

### ISSUE THREAD

**Issue by HaoZeke** [approvals/ApprovalTests.cpp#231]
Just wanted to add some notes about using `Catch2v3`.
- Distributed via `catch_amalgamated.{c,h}pp`

```cpp
#define APPROVALS_CATCH2_V3
#include "ApprovalTests.hpp"
```

So there's also this patch:
```diff
diff --git a/client/thirdparty/ApprovalTests.hpp b/client/thirdparty/ApprovalTests.hpp
index 35199074..025c94e6 100644
--- a/client/thirdparty/ApprovalTests.hpp
+++ b/client/thirdparty/ApprovalTests.hpp
@@ -2235,7 +2235,7 @@ namespace ApprovalTests
 #ifdef APPROVALS_CATCH
 #define APPROVAL_TESTS_INCLUDE_CPPS
 
-#include "catch2/catch_amalgamated.hpp"
+#include <catch2/catch.hpp>
 
 //namespace ApprovalTests {
 struct Catch2ApprovalListener : Catch::TestEventListenerBase
@@ -2307,7 +2307,10 @@ CATCH_REGISTER_LISTENER(Catch2TestCommitRevert)
 #ifdef APPROVALS_CATCH2_V3
 #define APPROVAL_TESTS_INCLUDE_CPPS
 
-#include "catch2/catch_amalgamated.hpp"
+#include <catch2/reporters/catch_reporter_event_listener.hpp>
+#include <catch2/catch_test_macros.hpp>
+#include <catch2/reporters/catch_reporter_registrars.hpp>
+#include <catch2/catch_test_case_info.hpp>
 
 //namespace ApprovalTests {
 struct Catch2ApprovalListener : Catch::EventListenerBase
```

... and that's it. Should have a docs PR soon.

**Comment by claremacrae** [comment]
Hello @HaoZeke,

Thanks very much for telling us about this, and for offering a PR on the documentation.

Rather than documenting a manual edit to the ApprovalTests.cpp code, we have made it so that the project will build with both Catch2 v3 layouts.

And the documentation is updated here:

https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/UsingCatch2v3.md

Basically, use `APPROVALS_CATCH2_V3_AMALGAMATED` in your `main.cpp` instead of `APPROVALS_CATCH2_V3`.

If you build against the `master` branch of this project, it should just work.

Otherwise, we may be able to do a release at the end of this month.

Thanks again.

**Comment by HaoZeke** [comment]
Thanks a ton for working on this, that's a much more elegant fix.
