### ISSUE TITLE
Use RAII also for comparators

### ISSUE THREAD

**Issue by mika-fischer** [approvals/ApprovalTests.cpp#42]
I really like the use of [DisposableObjects](https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/DisposableObjects.md) throughout the project. However, one place where they're missing is custom comparators...

This creates an issue for the way I try to use them:
What I want to do is to verify JSON data, but for the contained floating point values have some sort of tolerance applied to the comparison. So I have an `ApprovalComparator` that takes the tolerance as a parameter.

But then I have to globally register this comparator for some file extension:
```cpp
FileApprover::registerComparator(".json", std::make_shared<NumericJSONComparator>(Tolerance{1e-8}));
```

The problem is that this comparator is now used for all subsequent comparisons of JSON files. And that's not what I want (In fact forgetting to reset could lead to very hard to find false-positive tests...)

The workarounds I see are:
- Use a different extension for each tolerance (not at all nice)
- Write a RAII wrapper that manually resets the comparator to the default `TextFileComparator` (what I use for now)

```cpp
    class RegisterComparator {
        public:
            RegisterComparator(std::string extensionWithDot, std::shared_ptr<ApprovalTests::ApprovalComparator> comparator)
            : ext_(extensionWithDot)
            {
                ApprovalTests::FileApprover::registerComparator(ext_, comparator);
            }

            ~RegisterComparator() {
                ApprovalTests::FileApprover::registerComparator(ext_, std::make_shared<ApprovalTests::TextFileComparator>());
            }
        
        private:
            std::string ext_;
    };
```

But I think it would be cleaner if ApprovalTests included the RAII wrapper out-of-the-box and also that the wrapper reset the state to the state before (i.e. remove from map, instead of overwriting map element with default.

What do you think? Maybe I'm also misusing the custom comparators. If so, is there a better way to accomplish what I want?

**Comment by claremacrae** [comment]
Yes, I think these are all good points, and it was probably just historical...

FileApprover::registerComparator() was introduced [in v.3.0.0](https://github.com/approvals/ApprovalTests.cpp/releases/tag/v.3.0.0).

And from looking at all [the release logs](https://github.com/approvals/ApprovalTests.cpp/releases), this was pretty much our first customisation, and it was written to allow me to compare images, where I only cared about providing one new comparator for the lifetime of the project - so I think we may not have thought of using DisposableObjects at this stage...

**Comment by claremacrae** [comment]
Definite issues with the current implementation:

* adding new code that changes the comparator for an extension will change the comparator used for existing tests that are run later. As noted in the report above, this could break, or cause silent future spurious passes.
* it makes the behaviour of the tests non-deterministic if used with any testsuite facility that allows tests to be run in a random order.

This is because without the proposed RAII disposer, the current implementation any test that calls `ApprovalTests::FileApprover::registerComparator()` changes all the remaining comparisons of that file extension for the remainder of the session.

**Comment by claremacrae** [comment]
One small thing to note on the timing of doing this...

On a fork, I recently experimented with simplifying (in my view) how the various class static data members are initialised:
https://github.com/claremacrae/ApprovalTests.cpp/commits/simpler_static_data

This branch is awaiting time for me and Llewellyn to review it...

If it's accepted, then it would probably cause a (small) conflict between the fix for this issue and that branch...

So if this wasn't urgent, it would be a bit simpler to decide the fate of the above branch first...

**Comment by claremacrae** [comment]
This has just been released in v.6.0.0 - thanks for the request.
Please see the changelog for a change in function name...
