### ISSUE TITLE
Change Catch2 includes to catch2/catch.hpp

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.cpp#62]
From the current maintainer of Catch2, after we announced we had changed from Catch.hpp to catch.cpp:

"I strongly recommend going with #include "catch2/catch.hpp"

Because if you use Catch2 via CMake or having it installed, the include path will be <catch2/catch.hpp>"

**Comment by dheater** [comment]
I can confirm that I have experienced this problem.

**Comment by athrun22** [comment]
This is currently an issue for me as well. Including catch2 using ```FetchContent``` in CMake and linking against the ```Catch2::Catch2``` imported target will transitively add the include directory [single_include](https://github.com/catchorg/Catch2/tree/master/single_include/catch2) found in catch2. Because "single_include" is structured with the "catch.hpp" header under the "catch2" directory, dependent targets must include ```<catch2/catch.hpp>```.

**Comment by claremacrae** [comment]
@dheater @athrun22 Thanks for these comments - very helpful.

Various thoughts on this... Feedback welcomed, please...

I'm curious about the timing of these messages... We thought we had improved things by changing from Catch.hpp to catch.hpp - did the original name work OK for you, and this change mae it worse?

I'm unsure how we can keep supporting both Catch1 and Catch2. 

As far as I can see, Catch1 is traditionally included via:

#include "catch.hpp"

References:

* https://github.com/catchorg/Catch2/blob/Catch1.x/docs/tutorial.md
* https://github.com/catchorg/Catch2/tree/master/include

And Catch2:

`#include <catch2/catch.hpp>`

Reference:

* https://github.com/catchorg/Catch2/blob/master/docs/tutorial.md#top

Maybe we should drop support for Catch1, as we use some C++11 constructs in the library, so it's not really useful with C++98, as far as I can see.

Or maybe we should just use this:

`#include <catch2/catch.hpp>`

or this

`#include "catch2/catch.hpp"`

and in the unlikely event that anyone is using Catch1, they can create a wrapper header...

I'm also interested in comments on how we should manage the files in this project's third_party directory...

We currently have these two:

- `third_party/catch1/catch.hpp`
- `third_party/catch2/catch.hpp`
- `third_party/doctest/doctest.h`
- `third_party/ut/ut.hpp`

I'd like to keep them all as separate dependencies in our cmake files, by which I mean that adding an include-path for one should not accidentally enable the finding of any of the others...

So the best I can think of for the Catch header locations and search paths is:

- `third_party/catch1/catch.hpp` - adds `third_party/catch1` to include paths
- `third_party/catch2/catch2/catch.hpp` - adds ``third_party/catch2` to include paths

**Comment by dheater** [comment]
I just started using ApprovalTests, so I can't state whether the change in case has anything to do with it. I don't see how it would and lower case `catch.hpp` is *more* correct (case matches the file).

I'm inclined to drop Catch 1 support.

I was just working on a patch for this issue, and noticed that the `CatchApprovals.h` functions have the prefix `Catch2`.

I was going to use `CATCH_VERSION_MAJOR` to flag which path to use in `Catch2Approvals.h`, but that doesn't work since `CATCH_VERSION_MAJOR` isn't defined until I include the header...

We could have a copy of `Catch2Approvals.h` named `CatchApprovals.h` for version 1, with the right path, but that seems ugly.

We could expect the user to include the `catch.hpp` file if they are using Catch, but that would probably break compatibility.

**Comment by athrun22** [comment]
@claremacrae, my project setup uses CMake's ```FetchContent``` module to pull-in ApprovalTests as part of my project. It uses ```add_subdirectory``` to nest the ApprovalTests within my own project. My project also includes the appropriate Test Framework, whether it be Catch2 or Boost ut, using ```FetchContent``` and uses this instead of ApprovalTests bundled headers. This is why my use case runs into this issue. Perhaps using ```FetchContent``` to include the third party projects would do a better job of mirroring the expected include directories within the ApprovalTests project. It would also simplify upgrading the test framework versions since a new header doesn't have to be copied over every time. The git tag of the latest supported release would be updated instead.

**Comment by claremacrae** [comment]
Hi @athrun22  thanks for your input on this and other issues!

@dheater and I are planning to look at this issue more closely tomorrow...

Is your project is publicly visible, so that we can see the details of how it's set up, and try it ourselves. please?

**Comment by athrun22** [comment]
@claremacrae no problem, I find the project quite helpful so thank you 😃 Unfortunately, the project is proprietary 😔 But it is simple enough to replicate the CMake logic. I'll set up a mock project and send a link to the repository.

**Comment by balp** [comment]
I have an unrelated patch to @EmilyBache Lift kata, where I combined ApprovalTests with Catch2 in a modern CMake way. I added an IMHO ugly extra interface folder for catch2 to the approval test rules so it could find the interface, this patch will make the integration much cleaner. 

This is the magic I ended up with:

```cmake
target_include_directories(approvaltests
        INTERFACE ${CMAKE_CURRENT_BINARY_DIR}/approvaltests
        INTERFACE ${catch2_SOURCE_DIR}/single_include/catch2
        )
```

Link to the pull-request: https://github.com/emilybache/Lift-Kata/pull/3/commits/28f5124c5ddc7be6fd27f0b025c4c798b5b29aef or just my branch https://github.com/balp/Lift-Kata/tree/cpp

**Comment by athrun22** [comment]
@claremacrae, a sample project using CMake's ```FetchContent``` module can be found here -> https://github.com/athrun22/approval-tests-setup

**Comment by claremacrae** [comment]
@athrun22 Thanks!! I read through and it makes sense at first reading - I'll test it on my Mac shortly.

**Comment by balp** [comment]
@athrun22 Works fine on my MacBook/CLion. I would have avoided the global CXX versions, but it works.

The difference in working against the git structure gives me an idea on how to work with both CMake and Meson build framework.

**Comment by claremacrae** [comment]
It works on my Mac too, of course...

I see now that if we included the latest single_header release inside the ApprovalTests project (as catch2 does), it would be really easy for users to grab the latest release - thanks!

**Comment by balp** [comment]
@claremacrae I added meson to @athrun22 example here: https://github.com/balp/approval-tests-setup also made a small patch to https://github.com/balp/approval-tests-setup adding a meson.build file to make it simple to include. Not working with the single header file version as much more meson compatible.

**Comment by claremacrae** [comment]
Thanks @balp - really helpful!

**Comment by athrun22** [comment]
> @athrun22 Works fine on my MacBook/CLion. I would have avoided the global CXX versions, but it works.
@balp, yeah that's mostly out of habit / standard CMake practice rather than any real necessity for such a simple project.

@claremacrae, your welcome! I'm glad to help.
